name: MSBuild Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .

  # Change the BUILD_CONFIGURATION value for Linux, if needed.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest # Change to 'ubuntu-latest' for Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # Updated to v2

    - name: Install .NET SDK
      # Use this step to install the .NET SDK if required.
      # See: https://docs.github.com/actions/language-and-framework-guides/building-and-testing-net-core#building-net-core
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-7.0 # Change to the desired .NET SDK version

    - name: Restore NuGet packages
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: vcpkg
      run: |
        cd GameEngine
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh # Use .sh for Linux
        ./vcpkg/vcpkg integrate install

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}
